language: node_js
node_js:
  - "4.0"
script:
  - echo 'Hello Firebase'
install:
  # - mkdir /home/travis/tmp
  - sudo $(which npm) install -g firebase-tools
after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}